CREATE TABLE requests (
  id VARCHAR(24) PRIMARY KEY,
  host VARCHAR(24) NOT NULL,
  guest VARCHAR(24) NOT NULL,
  house VARCHAR(24) NOT NULL,
  accepted BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
